apiVersion: v1
kind: Namespace
metadata:
  name: sdfsdfsdf-staging
  labels:
    environment-id: env_ca637973-edae-406a-a2d6-d00caa69eb29
    project-id: project_b04b40c8-21dc-43f8-a741-9a403cb65a2f
    project-name: sdfsdfsdf
    environment-name: staging
    organization-id: org_1c58789b-c98c-4917-b321-116968ec4f8e
